components:
  schemas:
    HelloWorld:
      properties:
        text:
          type: string
      type: object
info:
  title: Swagger hello world
  version: 1.0.0
openapi: 3.0.2
paths:
  /hello_world/{num}:
    get:
      description: возвращяет hello_world
      parameters:
      - in: path
        name: num
        required: true
        schema:
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelloWorld'
          description: OK
  /data:
    get:
      description: Возвращает ровно то, что принимает
      responses:
        '200':
          description: OK
