components:
  schemas:
    HelloWorld:
      properties:
        text:
          type: string
      type: object
info:
  title: Swagger hello world
  version: 1.0.0
openapi: 3.0.2
paths:
  /hello_world
    get:
      description: Get a hello world massage
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelloWorld'
          description: OK
  /data:
    get:
      description: "\u0412\u043E\u0437\u0432\u0440\u0430\u0449\u0430\u0435\u0442 \u0440\
        \u043E\u0432\u043D\u043E \u0442\u043E, \u0447\u0442\u043E \u043F\u0440\u0438\
        \u043D\u0438\u043C\u0430\u0435\u0442"
      responses:
        '200':
          description: OK
